version: 1
formatters:
  default:
        format: "%(asctime)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: logs/app.log
    maxBytes: 10000 #10mb
    backupCount: 3

loggers:
  console:
    level: DEBUG
    handlers: [console]
    propagate: no

  file:
    level: DEBUG
    handlers: [file]
    propagate: no

root:
    level: DEBUG
    handlers: [file, console]


